# Object Detection (YOLOv8)
detection:
  model: yolov8x.pt
  confidence_threshold: 0.6
  iou_threshold: 0.5
  input_size: 640

# Pose Estimation (MediaPipe)
pose:
  complexity: 2
  min_detection_confidence: 0.7
  enable_segmentation: True

# Tracking (DeepSORT)
tracking:
  max_age: 30
  embedder: mobilenet
  max_cosine_distance: 0.4

training:
  epochs: 100
  batch_size: 16
  optimizer: AdamW
  learning_rate: 0.001
  early_stopping: 25
  experiment_name: "visionflow_v1"

device: "0"  # GPU ID or "cpu"
data: "data/dataset.yaml"